# Generated by Django 5.2.7 on 2025-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=10)),
                ('name', models.TextField(max_length=100)),
                ('dimension', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('supplier', models.CharField(max_length=50)),
                ('prod', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
